release: python manage.py migrate && python manage.py collectstatic --noinput
web: exec gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --log-file=- --access-logfile=- --error-logfile=- --log-level info --capture-output 2>&1
