# Generated by Django 5.0.1 on 2025-11-01 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("item", models.CharField(max_length=255, verbose_name="예산 항목명")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="금액",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "quarter",
                    models.IntegerField(blank=True, null=True, verbose_name="분기"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="상세 설명"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="budgets",
                        to="accounts.userprofile",
                        verbose_name="업로드한 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "예산",
                "verbose_name_plural": "예산 목록",
                "db_table": "budgets",
                "ordering": ["-fiscal_year", "-quarter"],
                "indexes": [
                    models.Index(
                        fields=["fiscal_year", "category"],
                        name="budgets_fiscal__0a4900_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="budgets_uploade_f4fdc4_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="budgets_is_dele_d8361f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="논문 제목")),
                ("authors", models.TextField(verbose_name="저자 목록")),
                ("publication_date", models.DateField(verbose_name="게재일")),
                ("field", models.CharField(max_length=100, verbose_name="분야")),
                (
                    "journal_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="학술지명"
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="DOI",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="papers",
                        to="accounts.userprofile",
                        verbose_name="업로드한 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "논문",
                "verbose_name_plural": "논문 목록",
                "db_table": "papers",
                "ordering": ["-publication_date"],
                "indexes": [
                    models.Index(
                        fields=["publication_date", "field"],
                        name="papers_publica_f47de3_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="papers_uploade_8eb6a0_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="papers_is_dele_7cb25f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("date", models.DateField(verbose_name="실적 발생 날짜")),
                ("title", models.CharField(max_length=255, verbose_name="실적 항목명")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="금액",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="카테고리")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="상세 설명"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="performances",
                        to="accounts.userprofile",
                        verbose_name="업로드한 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "실적",
                "verbose_name_plural": "실적 목록",
                "db_table": "performances",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["date", "category"], name="performance_date_def4e2_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="performance_uploade_8c0a88_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="performance_is_dele_5bfe9d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="학번"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="학생 이름")),
                ("department", models.CharField(max_length=100, verbose_name="학과")),
                (
                    "grade",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="학년",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "재학"),
                            ("graduated", "졸업"),
                            ("withdrawn", "자퇴"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="students",
                        to="accounts.userprofile",
                        verbose_name="업로드한 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "학생",
                "verbose_name_plural": "학생 목록",
                "db_table": "students",
                "ordering": ["student_id"],
                "indexes": [
                    models.Index(
                        fields=["department", "grade"],
                        name="students_departm_b33137_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="students_uploade_7ce475_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="students_is_dele_51b572_idx"
                    ),
                ],
            },
        ),
    ]
