# -*- coding: utf-8 -*-
# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('date', models.DateField(verbose_name='실적 발생 날짜')),
                ('title', models.CharField(max_length=255, verbose_name='실적 항목명')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='금액')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상세 설명')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='performances', to='accounts.userprofile', verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '실적',
                'verbose_name_plural': '실적 목록',
                'db_table': 'performances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=500, verbose_name='논문 제목')),
                ('authors', models.TextField(verbose_name='저자 목록')),
                ('publication_date', models.DateField(verbose_name='게재일')),
                ('field', models.CharField(max_length=100, verbose_name='분야')),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='학술지명')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='DOI')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='papers', to='accounts.userprofile', verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '논문',
                'verbose_name_plural': '논문 목록',
                'db_table': 'papers',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='학번')),
                ('name', models.CharField(max_length=100, verbose_name='학생 이름')),
                ('department', models.CharField(max_length=100, verbose_name='학과')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='학년')),
                ('status', models.CharField(choices=[('active', '재학'), ('graduated', '졸업'), ('withdrawn', '자퇴')], default='active', max_length=20, verbose_name='상태')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='accounts.userprofile', verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생 목록',
                'db_table': 'students',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('item', models.CharField(max_length=255, verbose_name='예산 항목명')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='금액')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('fiscal_year', models.IntegerField(verbose_name='회계연도')),
                ('quarter', models.IntegerField(blank=True, null=True, verbose_name='분기')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상세 설명')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='budgets', to='accounts.userprofile', verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '예산',
                'verbose_name_plural': '예산 목록',
                'db_table': 'budgets',
                'ordering': ['-fiscal_year', '-quarter'],
            },
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['date', 'category'], name='performance_date_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['uploaded_by'], name='performance_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['is_deleted'], name='performance_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['publication_date', 'field'], name='paper_pub_field_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['uploaded_by'], name='paper_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['is_deleted'], name='paper_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department', 'grade'], name='student_dept_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['uploaded_by'], name='student_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_deleted'], name='student_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['fiscal_year', 'category'], name='budget_year_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['uploaded_by'], name='budget_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['is_deleted'], name='budget_deleted_idx'),
        ),
    ]
