# Generated by Django 5.0.1 on 2025-11-03 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("date", models.DateField(verbose_name="실적 날짜")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="실적 금액",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="실적 분류"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="부서명"
                    ),
                ),
            ],
            options={
                "verbose_name": "실적",
                "verbose_name_plural": "실적 목록",
                "db_table": "performance",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "paper_id",
                    models.CharField(
                        help_text="PUB-YY-NNN 형식",
                        max_length=50,
                        unique=True,
                        verbose_name="논문ID",
                    ),
                ),
                ("publication_date", models.DateField(verbose_name="게재일")),
                ("college", models.CharField(max_length=100, verbose_name="단과대학")),
                ("department", models.CharField(max_length=100, verbose_name="학과")),
                (
                    "paper_title",
                    models.TextField(help_text="1~500자", verbose_name="논문 제목"),
                ),
                ("lead_author", models.CharField(max_length=100, verbose_name="주저자")),
                (
                    "co_authors",
                    models.TextField(
                        blank=True,
                        help_text="세미콜론으로 구분",
                        null=True,
                        verbose_name="참여저자",
                    ),
                ),
                ("journal_name", models.CharField(max_length=200, verbose_name="학술지명")),
                (
                    "journal_grade",
                    models.CharField(
                        choices=[("SCIE", "SCIE"), ("KCI", "KCI")],
                        max_length=10,
                        verbose_name="저널 등급",
                    ),
                ),
                (
                    "impact_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="SCIE만 필수, KCI는 NULL",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Impact Factor",
                    ),
                ),
                (
                    "project_linked",
                    models.CharField(
                        choices=[("Y", "연계"), ("N", "비연계")],
                        max_length=1,
                        verbose_name="과제연계여부",
                    ),
                ),
            ],
            options={
                "verbose_name": "논문",
                "verbose_name_plural": "논문 목록",
                "db_table": "publication",
                "ordering": ["-publication_date"],
            },
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "execution_id",
                    models.CharField(
                        help_text="T2324NNN 형식",
                        max_length=50,
                        unique=True,
                        verbose_name="집행ID",
                    ),
                ),
                (
                    "project_number",
                    models.CharField(
                        help_text="예: NRF-2023-015", max_length=100, verbose_name="과제번호"
                    ),
                ),
                ("project_name", models.CharField(max_length=200, verbose_name="과제명")),
                (
                    "principal_investigator",
                    models.CharField(max_length=100, verbose_name="연구책임자"),
                ),
                ("department", models.CharField(max_length=100, verbose_name="소속학과")),
                (
                    "funding_agency",
                    models.CharField(max_length=100, verbose_name="지원기관"),
                ),
                (
                    "total_budget",
                    models.BigIntegerField(
                        help_text="원 단위",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="총 연구비",
                    ),
                ),
                ("execution_date", models.DateField(verbose_name="집행일자")),
                (
                    "execution_item",
                    models.CharField(max_length=200, verbose_name="집행 항목"),
                ),
                (
                    "execution_amount",
                    models.BigIntegerField(
                        help_text="원 단위",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="집행 금액",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("집행완료", "집행완료"), ("처리중", "처리중")],
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="비고")),
            ],
            options={
                "verbose_name": "연구 과제",
                "verbose_name_plural": "연구 과제 목록",
                "db_table": "research_project",
                "ordering": ["-execution_date"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="YYYYMMNNN 형식",
                        max_length=20,
                        unique=True,
                        verbose_name="학번",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("college", models.CharField(max_length=100, verbose_name="단과대학")),
                ("department", models.CharField(max_length=100, verbose_name="학과")),
                (
                    "grade",
                    models.IntegerField(
                        help_text="학사: 1~4, 석사/박사: 0",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="학년",
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[("학사", "학사"), ("석사", "석사"), ("박사", "박사")],
                        max_length=10,
                        verbose_name="과정 구분",
                    ),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[("재학", "재학"), ("휴학", "휴학"), ("졸업", "졸업")],
                        max_length=10,
                        verbose_name="학적 상태",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("남", "남"), ("여", "여")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                (
                    "admission_year",
                    models.IntegerField(
                        help_text="2015~2025",
                        validators=[
                            django.core.validators.MinValueValidator(2015),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                        verbose_name="입학년도",
                    ),
                ),
                (
                    "advisor",
                    models.CharField(
                        blank=True,
                        help_text="학부생은 NULL 가능",
                        max_length=100,
                        null=True,
                        verbose_name="지도교수",
                    ),
                ),
                ("email", models.EmailField(max_length=100, verbose_name="이메일")),
            ],
            options={
                "verbose_name": "학생",
                "verbose_name_plural": "학생 목록",
                "db_table": "student",
                "ordering": ["student_id"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "evaluation_year",
                    models.IntegerField(help_text="2020~2030 범위", verbose_name="평가년도"),
                ),
                ("college", models.CharField(max_length=100, verbose_name="단과대학")),
                ("department", models.CharField(max_length=100, verbose_name="학과")),
                (
                    "employment_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="%, 소수점 2자리",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="졸업생 취업률",
                    ),
                ),
                (
                    "full_time_faculty",
                    models.IntegerField(
                        help_text="명",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="전임교원 수",
                    ),
                ),
                (
                    "visiting_faculty",
                    models.IntegerField(
                        help_text="명",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="초빙교원 수",
                    ),
                ),
                (
                    "tech_transfer_income",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="억원 단위",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="기술이전 수입액",
                    ),
                ),
                (
                    "intl_conferences",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="국제학술대회 개최 횟수",
                    ),
                ),
            ],
            options={
                "verbose_name": "학과 KPI 데이터",
                "verbose_name_plural": "학과 KPI 데이터 목록",
                "db_table": "department_kpi",
                "ordering": ["-evaluation_year", "college", "department"],
                "indexes": [
                    models.Index(fields=["evaluation_year"], name="idx_dept_kpi_year"),
                    models.Index(fields=["department"], name="idx_dept_kpi_dept"),
                    models.Index(fields=["college"], name="idx_dept_kpi_college"),
                    models.Index(
                        fields=["evaluation_year", "college"],
                        name="idx_dept_kpi_year_college",
                    ),
                    models.Index(fields=["created_at"], name="idx_dept_kpi_created"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="departmentkpi",
            constraint=models.UniqueConstraint(
                fields=("evaluation_year", "department"),
                name="uk_department_kpi_year_dept",
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(fields=["date"], name="idx_perf_date"),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(fields=["department"], name="idx_perf_dept"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["publication_date"], name="idx_pub_date"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["department"], name="idx_pub_dept"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["college"], name="idx_pub_college"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["journal_grade"], name="idx_pub_grade"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["project_linked"], name="idx_pub_linked"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["created_at"], name="idx_pub_created"),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(fields=["project_number"], name="idx_rp_project_number"),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(fields=["principal_investigator"], name="idx_rp_pi"),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(fields=["department"], name="idx_rp_dept"),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(fields=["funding_agency"], name="idx_rp_agency"),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(fields=["execution_date"], name="idx_rp_date"),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(fields=["status"], name="idx_rp_status"),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(
                fields=["project_number", "execution_date"], name="idx_rp_project_date"
            ),
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(fields=["execution_item"], name="idx_rp_item"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["department"], name="idx_student_dept"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["college"], name="idx_student_college"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["program_type"], name="idx_student_program"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["enrollment_status"], name="idx_student_status"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["grade"], name="idx_student_grade"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["admission_year"], name="idx_student_admission"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["department", "enrollment_status"],
                name="idx_student_dept_status",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["gender"], name="idx_student_gender"),
        ),
    ]
