# Generated by Django 5.0.1 on 2025-11-03 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="파일명")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("department_kpi", "학과 KPI 데이터"),
                            ("publication", "논문 목록"),
                            ("research_project", "연구 과제 데이터"),
                            ("student_roster", "학생 명단"),
                        ],
                        max_length=50,
                        verbose_name="데이터 유형",
                    ),
                ),
                (
                    "rows_processed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="처리된 행 수",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "전체 성공"),
                            ("partial", "부분 성공"),
                            ("failed", "전체 실패"),
                        ],
                        max_length=20,
                        verbose_name="업로드 상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="오류 메시지"),
                ),
                (
                    "uploaded_by",
                    models.CharField(max_length=100, verbose_name="업로드 사용자"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 일시"),
                ),
            ],
            options={
                "verbose_name": "업로드 이력",
                "verbose_name_plural": "업로드 이력 목록",
                "db_table": "upload_history",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["uploaded_at"], name="idx_upload_history_date"
                    ),
                    models.Index(fields=["data_type"], name="idx_upload_history_type"),
                    models.Index(fields=["status"], name="idx_upload_history_status"),
                    models.Index(
                        fields=["uploaded_by"], name="idx_upload_history_user"
                    ),
                ],
            },
        ),
    ]
