# Generated by Django 5.0.1 on 2025-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="파일명")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("performance", "실적"),
                            ("paper", "논문"),
                            ("student", "학생"),
                            ("budget", "예산"),
                        ],
                        max_length=50,
                        verbose_name="데이터 유형",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기 (bytes)"),
                ),
                (
                    "rows_processed",
                    models.IntegerField(default=0, verbose_name="처리된 행 수"),
                ),
                ("rows_failed", models.IntegerField(default=0, verbose_name="실패한 행 수")),
                (
                    "uploaded_by",
                    models.CharField(max_length=255, verbose_name="업로드 사용자 이메일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("processing", "처리 중"),
                            ("success", "성공"),
                            ("failed", "실패"),
                            ("partial", "부분 성공"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="오류 메시지"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료 일시"),
                ),
            ],
            options={
                "verbose_name": "업로드된 파일",
                "verbose_name_plural": "업로드된 파일 목록",
                "db_table": "uploaded_files",
                "ordering": ["-created_at"],
            },
        ),
    ]
